<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Tous les pays ISO 3166-1 alpha-2 avec leur devise par défaut.
     * Format : [code, name, flag_emoji, phone_code, currency_code]
     */
    public function run(): void
    {
        foreach ($this->countries() as $row) {
            Country::updateOrCreate(
                ['code' => $row[0]],
                [
                    'name' => $row[1],
                    'flag_emoji' => $row[2],
                    'phone_code' => $row[3],
                    'currency_code' => $row[4],
                    'is_active' => true,
                ]
            );
        }
    }

    private function countries(): array
    {
        return [
            // Afrique de l'Ouest (CFA BCEAO)
            ['BJ', 'Bénin',          '🇧🇯', '+229', 'XOF'],
            ['BF', 'Burkina Faso',   '🇧🇫', '+226', 'XOF'],
            ['CI', 'Côte d\'Ivoire', '🇨🇮', '+225', 'XOF'],
            ['GW', 'Guinée-Bissau',  '🇬🇼', '+245', 'XOF'],
            ['ML', 'Mali',           '🇲🇱', '+223', 'XOF'],
            ['NE', 'Niger',          '🇳🇪', '+227', 'XOF'],
            ['SN', 'Sénégal',        '🇸🇳', '+221', 'XOF'],
            ['TG', 'Togo',           '🇹🇬', '+228', 'XOF'],

            // Afrique centrale (CFA BEAC)
            ['CM', 'Cameroun',                  '🇨🇲', '+237', 'XAF'],
            ['CF', 'République centrafricaine', '🇨🇫', '+236', 'XAF'],
            ['TD', 'Tchad',                     '🇹🇩', '+235', 'XAF'],
            ['CG', 'République du Congo',       '🇨🇬', '+242', 'XAF'],
            ['GQ', 'Guinée équatoriale',        '🇬🇶', '+240', 'XAF'],
            ['GA', 'Gabon',                     '🇬🇦', '+241', 'XAF'],

            // Reste de l'Afrique
            ['DZ', 'Algérie',                            '🇩🇿', '+213', 'DZD'],
            ['AO', 'Angola',                             '🇦🇴', '+244', 'AOA'],
            ['BW', 'Botswana',                           '🇧🇼', '+267', 'BWP'],
            ['BI', 'Burundi',                            '🇧🇮', '+257', 'BIF'],
            ['CV', 'Cap-Vert',                           '🇨🇻', '+238', 'CVE'],
            ['KM', 'Comores',                            '🇰🇲', '+269', 'KMF'],
            ['CD', 'République démocratique du Congo',   '🇨🇩', '+243', 'CDF'],
            ['DJ', 'Djibouti',                           '🇩🇯', '+253', 'DJF'],
            ['EG', 'Égypte',                             '🇪🇬', '+20',  'EGP'],
            ['ER', 'Érythrée',                           '🇪🇷', '+291', 'ERN'],
            ['SZ', 'Eswatini',                           '🇸🇿', '+268', 'SZL'],
            ['ET', 'Éthiopie',                           '🇪🇹', '+251', 'ETB'],
            ['GM', 'Gambie',                             '🇬🇲', '+220', 'GMD'],
            ['GH', 'Ghana',                              '🇬🇭', '+233', 'GHS'],
            ['GN', 'Guinée',                             '🇬🇳', '+224', 'GNF'],
            ['KE', 'Kenya',                              '🇰🇪', '+254', 'KES'],
            ['LS', 'Lesotho',                            '🇱🇸', '+266', 'LSL'],
            ['LR', 'Libéria',                            '🇱🇷', '+231', 'LRD'],
            ['LY', 'Libye',                              '🇱🇾', '+218', 'LYD'],
            ['MG', 'Madagascar',                         '🇲🇬', '+261', 'MGA'],
            ['MW', 'Malawi',                             '🇲🇼', '+265', 'MWK'],
            ['MR', 'Mauritanie',                         '🇲🇷', '+222', 'MRU'],
            ['MU', 'Maurice',                            '🇲🇺', '+230', 'MUR'],
            ['MA', 'Maroc',                              '🇲🇦', '+212', 'MAD'],
            ['MZ', 'Mozambique',                         '🇲🇿', '+258', 'MZN'],
            ['NA', 'Namibie',                            '🇳🇦', '+264', 'NAD'],
            ['NG', 'Nigéria',                            '🇳🇬', '+234', 'NGN'],
            ['RW', 'Rwanda',                             '🇷🇼', '+250', 'RWF'],
            ['ST', 'São Tomé-et-Principe',               '🇸🇹', '+239', 'STN'],
            ['SC', 'Seychelles',                         '🇸🇨', '+248', 'SCR'],
            ['SL', 'Sierra Leone',                       '🇸🇱', '+232', 'SLE'],
            ['SO', 'Somalie',                            '🇸🇴', '+252', 'SOS'],
            ['ZA', 'Afrique du Sud',                     '🇿🇦', '+27',  'ZAR'],
            ['SS', 'Soudan du Sud',                      '🇸🇸', '+211', 'SSP'],
            ['SD', 'Soudan',                             '🇸🇩', '+249', 'SDG'],
            ['TZ', 'Tanzanie',                           '🇹🇿', '+255', 'TZS'],
            ['TN', 'Tunisie',                            '🇹🇳', '+216', 'TND'],
            ['UG', 'Ouganda',                            '🇺🇬', '+256', 'UGX'],
            ['ZM', 'Zambie',                             '🇿🇲', '+260', 'ZMW'],
            ['ZW', 'Zimbabwe',                           '🇿🇼', '+263', 'ZWL'],

            // Europe
            ['AL', 'Albanie',                  '🇦🇱', '+355',  'ALL'],
            ['AD', 'Andorre',                  '🇦🇩', '+376',  'EUR'],
            ['AT', 'Autriche',                 '🇦🇹', '+43',   'EUR'],
            ['BY', 'Biélorussie',              '🇧🇾', '+375',  'BYN'],
            ['BE', 'Belgique',                 '🇧🇪', '+32',   'EUR'],
            ['BA', 'Bosnie-Herzégovine',       '🇧🇦', '+387',  'BAM'],
            ['BG', 'Bulgarie',                 '🇧🇬', '+359',  'BGN'],
            ['HR', 'Croatie',                  '🇭🇷', '+385',  'EUR'],
            ['CY', 'Chypre',                   '🇨🇾', '+357',  'EUR'],
            ['CZ', 'République tchèque',       '🇨🇿', '+420',  'CZK'],
            ['DK', 'Danemark',                 '🇩🇰', '+45',   'DKK'],
            ['EE', 'Estonie',                  '🇪🇪', '+372',  'EUR'],
            ['FI', 'Finlande',                 '🇫🇮', '+358',  'EUR'],
            ['FR', 'France',                   '🇫🇷', '+33',   'EUR'],
            ['DE', 'Allemagne',                '🇩🇪', '+49',   'EUR'],
            ['GR', 'Grèce',                    '🇬🇷', '+30',   'EUR'],
            ['HU', 'Hongrie',                  '🇭🇺', '+36',   'HUF'],
            ['IS', 'Islande',                  '🇮🇸', '+354',  'ISK'],
            ['IE', 'Irlande',                  '🇮🇪', '+353',  'EUR'],
            ['IT', 'Italie',                   '🇮🇹', '+39',   'EUR'],
            ['XK', 'Kosovo',                   '🇽🇰', '+383',  'EUR'],
            ['LV', 'Lettonie',                 '🇱🇻', '+371',  'EUR'],
            ['LI', 'Liechtenstein',            '🇱🇮', '+423',  'CHF'],
            ['LT', 'Lituanie',                 '🇱🇹', '+370',  'EUR'],
            ['LU', 'Luxembourg',               '🇱🇺', '+352',  'EUR'],
            ['MT', 'Malte',                    '🇲🇹', '+356',  'EUR'],
            ['MD', 'Moldavie',                 '🇲🇩', '+373',  'MDL'],
            ['MC', 'Monaco',                   '🇲🇨', '+377',  'EUR'],
            ['ME', 'Monténégro',               '🇲🇪', '+382',  'EUR'],
            ['NL', 'Pays-Bas',                 '🇳🇱', '+31',   'EUR'],
            ['MK', 'Macédoine du Nord',        '🇲🇰', '+389',  'MKD'],
            ['NO', 'Norvège',                  '🇳🇴', '+47',   'NOK'],
            ['PL', 'Pologne',                  '🇵🇱', '+48',   'PLN'],
            ['PT', 'Portugal',                 '🇵🇹', '+351',  'EUR'],
            ['RO', 'Roumanie',                 '🇷🇴', '+40',   'RON'],
            ['RU', 'Russie',                   '🇷🇺', '+7',    'RUB'],
            ['SM', 'Saint-Marin',              '🇸🇲', '+378',  'EUR'],
            ['RS', 'Serbie',                   '🇷🇸', '+381',  'RSD'],
            ['SK', 'Slovaquie',                '🇸🇰', '+421',  'EUR'],
            ['SI', 'Slovénie',                 '🇸🇮', '+386',  'EUR'],
            ['ES', 'Espagne',                  '🇪🇸', '+34',   'EUR'],
            ['SE', 'Suède',                    '🇸🇪', '+46',   'SEK'],
            ['CH', 'Suisse',                   '🇨🇭', '+41',   'CHF'],
            ['UA', 'Ukraine',                  '🇺🇦', '+380',  'UAH'],
            ['GB', 'Royaume-Uni',              '🇬🇧', '+44',   'GBP'],
            ['VA', 'Vatican',                  '🇻🇦', '+379',  'EUR'],

            // Amérique du Nord
            ['CA', 'Canada',         '🇨🇦', '+1',   'CAD'],
            ['MX', 'Mexique',        '🇲🇽', '+52',  'MXN'],
            ['US', 'États-Unis',     '🇺🇸', '+1',   'USD'],

            // Amérique centrale & Caraïbes
            ['AG', 'Antigua-et-Barbuda',         '🇦🇬', '+1268', 'XCD'],
            ['BS', 'Bahamas',                    '🇧🇸', '+1242', 'BSD'],
            ['BB', 'Barbade',                    '🇧🇧', '+1246', 'BBD'],
            ['BZ', 'Belize',                     '🇧🇿', '+501',  'BZD'],
            ['CR', 'Costa Rica',                 '🇨🇷', '+506',  'CRC'],
            ['CU', 'Cuba',                       '🇨🇺', '+53',   'CUP'],
            ['DM', 'Dominique',                  '🇩🇲', '+1767', 'XCD'],
            ['DO', 'République dominicaine',     '🇩🇴', '+1809', 'DOP'],
            ['SV', 'Salvador',                   '🇸🇻', '+503',  'USD'],
            ['GD', 'Grenade',                    '🇬🇩', '+1473', 'XCD'],
            ['GT', 'Guatemala',                  '🇬🇹', '+502',  'GTQ'],
            ['HT', 'Haïti',                      '🇭🇹', '+509',  'HTG'],
            ['HN', 'Honduras',                   '🇭🇳', '+504',  'HNL'],
            ['JM', 'Jamaïque',                   '🇯🇲', '+1876', 'JMD'],
            ['NI', 'Nicaragua',                  '🇳🇮', '+505',  'NIO'],
            ['PA', 'Panama',                     '🇵🇦', '+507',  'PAB'],
            ['KN', 'Saint-Kitts-et-Nevis',       '🇰🇳', '+1869', 'XCD'],
            ['LC', 'Sainte-Lucie',               '🇱🇨', '+1758', 'XCD'],
            ['VC', 'Saint-Vincent-Grenadines',   '🇻🇨', '+1784', 'XCD'],
            ['TT', 'Trinité-et-Tobago',          '🇹🇹', '+1868', 'TTD'],
            ['AW', 'Aruba',                      '🇦🇼', '+297',  'AWG'],
            ['KY', 'Îles Caïmans',               '🇰🇾', '+1345', 'KYD'],
            ['BM', 'Bermudes',                   '🇧🇲', '+1441', 'BMD'],

            // Amérique du Sud
            ['AR', 'Argentine',  '🇦🇷', '+54',  'ARS'],
            ['BO', 'Bolivie',    '🇧🇴', '+591', 'BOB'],
            ['BR', 'Brésil',     '🇧🇷', '+55',  'BRL'],
            ['CL', 'Chili',      '🇨🇱', '+56',  'CLP'],
            ['CO', 'Colombie',   '🇨🇴', '+57',  'COP'],
            ['EC', 'Équateur',   '🇪🇨', '+593', 'USD'],
            ['GY', 'Guyana',     '🇬🇾', '+592', 'GYD'],
            ['PY', 'Paraguay',   '🇵🇾', '+595', 'PYG'],
            ['PE', 'Pérou',      '🇵🇪', '+51',  'PEN'],
            ['SR', 'Suriname',   '🇸🇷', '+597', 'SRD'],
            ['UY', 'Uruguay',    '🇺🇾', '+598', 'UYU'],
            ['VE', 'Venezuela',  '🇻🇪', '+58',  'VES'],

            // Asie
            ['AF', 'Afghanistan',        '🇦🇫', '+93',  'AFN'],
            ['AM', 'Arménie',            '🇦🇲', '+374', 'AMD'],
            ['AZ', 'Azerbaïdjan',        '🇦🇿', '+994', 'AZN'],
            ['BH', 'Bahreïn',            '🇧🇭', '+973', 'BHD'],
            ['BD', 'Bangladesh',         '🇧🇩', '+880', 'BDT'],
            ['BT', 'Bhoutan',            '🇧🇹', '+975', 'BTN'],
            ['BN', 'Brunei',             '🇧🇳', '+673', 'BND'],
            ['KH', 'Cambodge',           '🇰🇭', '+855', 'KHR'],
            ['CN', 'Chine',              '🇨🇳', '+86',  'CNY'],
            ['GE', 'Géorgie',            '🇬🇪', '+995', 'GEL'],
            ['HK', 'Hong Kong',          '🇭🇰', '+852', 'HKD'],
            ['IN', 'Inde',               '🇮🇳', '+91',  'INR'],
            ['ID', 'Indonésie',          '🇮🇩', '+62',  'IDR'],
            ['IR', 'Iran',               '🇮🇷', '+98',  'IRR'],
            ['IQ', 'Irak',               '🇮🇶', '+964', 'IQD'],
            ['IL', 'Israël',             '🇮🇱', '+972', 'ILS'],
            ['JP', 'Japon',              '🇯🇵', '+81',  'JPY'],
            ['JO', 'Jordanie',           '🇯🇴', '+962', 'JOD'],
            ['KZ', 'Kazakhstan',         '🇰🇿', '+7',   'KZT'],
            ['KW', 'Koweït',             '🇰🇼', '+965', 'KWD'],
            ['KG', 'Kirghizistan',       '🇰🇬', '+996', 'KGS'],
            ['LA', 'Laos',               '🇱🇦', '+856', 'LAK'],
            ['LB', 'Liban',              '🇱🇧', '+961', 'LBP'],
            ['MO', 'Macao',              '🇲🇴', '+853', 'MOP'],
            ['MY', 'Malaisie',           '🇲🇾', '+60',  'MYR'],
            ['MV', 'Maldives',           '🇲🇻', '+960', 'MVR'],
            ['MN', 'Mongolie',           '🇲🇳', '+976', 'MNT'],
            ['MM', 'Myanmar',            '🇲🇲', '+95',  'MMK'],
            ['NP', 'Népal',              '🇳🇵', '+977', 'NPR'],
            ['KP', 'Corée du Nord',      '🇰🇵', '+850', 'KPW'],
            ['OM', 'Oman',               '🇴🇲', '+968', 'OMR'],
            ['PK', 'Pakistan',           '🇵🇰', '+92',  'PKR'],
            ['PS', 'Palestine',          '🇵🇸', '+970', 'ILS'],
            ['PH', 'Philippines',        '🇵🇭', '+63',  'PHP'],
            ['QA', 'Qatar',              '🇶🇦', '+974', 'QAR'],
            ['SA', 'Arabie saoudite',    '🇸🇦', '+966', 'SAR'],
            ['SG', 'Singapour',          '🇸🇬', '+65',  'SGD'],
            ['KR', 'Corée du Sud',       '🇰🇷', '+82',  'KRW'],
            ['LK', 'Sri Lanka',          '🇱🇰', '+94',  'LKR'],
            ['SY', 'Syrie',              '🇸🇾', '+963', 'SYP'],
            ['TW', 'Taïwan',             '🇹🇼', '+886', 'TWD'],
            ['TJ', 'Tadjikistan',        '🇹🇯', '+992', 'TJS'],
            ['TH', 'Thaïlande',          '🇹🇭', '+66',  'THB'],
            ['TR', 'Turquie',            '🇹🇷', '+90',  'TRY'],
            ['TM', 'Turkménistan',       '🇹🇲', '+993', 'TMT'],
            ['AE', 'Émirats arabes unis', '🇦🇪', '+971', 'AED'],
            ['UZ', 'Ouzbékistan',        '🇺🇿', '+998', 'UZS'],
            ['VN', 'Vietnam',            '🇻🇳', '+84',  'VND'],
            ['YE', 'Yémen',              '🇾🇪', '+967', 'YER'],

            // Océanie
            ['AU', 'Australie',                  '🇦🇺', '+61',  'AUD'],
            ['FJ', 'Fidji',                      '🇫🇯', '+679', 'FJD'],
            ['KI', 'Kiribati',                   '🇰🇮', '+686', 'AUD'],
            ['MH', 'Îles Marshall',              '🇲🇭', '+692', 'USD'],
            ['FM', 'Micronésie',                 '🇫🇲', '+691', 'USD'],
            ['NR', 'Nauru',                      '🇳🇷', '+674', 'AUD'],
            ['NZ', 'Nouvelle-Zélande',           '🇳🇿', '+64',  'NZD'],
            ['PW', 'Palaos',                     '🇵🇼', '+680', 'USD'],
            ['PG', 'Papouasie-Nouvelle-Guinée',  '🇵🇬', '+675', 'PGK'],
            ['WS', 'Samoa',                      '🇼🇸', '+685', 'WST'],
            ['SB', 'Îles Salomon',               '🇸🇧', '+677', 'SBD'],
            ['TO', 'Tonga',                      '🇹🇴', '+676', 'TOP'],
            ['TV', 'Tuvalu',                     '🇹🇻', '+688', 'AUD'],
            ['VU', 'Vanuatu',                    '🇻🇺', '+678', 'VUV'],
        ];
    }
}
